### PR TITLE
Multi table node id support

### PR DESCRIPTION
**Pull request by jlark**
Updates:
-  Modified bulk posting to work with different tables. Consequently the BULK_INDEX_MAPPING configuration has changed to reflect a table based on the nodeid. 
- Updated CI testing to reflect this
- Changed Bulkpost to use POST rather than GET, as data getting pushed can get too big for GET.
- site_id is now a mandatory parameter 
- Changed time field to timestamp

TODO:
- Create new end points to handle status messages from RMC unit
- Make mechanism for hardcoded fields better. Site_id, timestamp? Should these be configurable?work with defaults?

### CODE REVIEW

**Comment by jlark** [comment]
Merged

**Comment by bumi** [comment]
sorry missed this PR. I've added some comments somewhere in the commits. Did you get the notification?

**Comment by bumi** [comment]
what was the `node_id` again?

**Comment by jlark** [comment]
Ok , Just seeing the comments now.

Node_id represents a sensor node. For Example: given site A: there can be multiple sensors nodes on the rmc. In our current setup we have a wireless temperature/humidity sensor, we have a dc battery sensor and the AC side sensor. All have different node id's and can send data in packets combined with other nodes. 

Consequently the mapping from Node_id=1 will be different to that of Node_id=1.

Let me know if that makes sense as this is quite important piece of the overall arch.

**Comment by bumi** [comment]
ok, thanks a lot for the explanation. so I basically can think of a node as a sensor on the unit. 

so parsing the request data would actually depend on the node and the DB in which we want to write the data.

**Comment by jlark** [comment]
Just a slight correction, you can think of a node as a cluster of sensors.

Yes parsing the request is a bit different as each node will have a different mapping and a different table. Because, for example a temperature node might update more often then an AC circuit node. Though the data get's all thrown into the same array and sent across.

**Pull request merged**
