### PR TITLE
fixed a few small bugs in prod influxdb timestamp

### PR DESCRIPTION
**Pull request by jlark**
Fixed: Looks like there was an error in merging. Table name wasn't getting parsed down to insert_mysql()
Fixed: Timestamp was incorrect for influx

@bumi how do you do the CI  testing with influx? Which server are you connecting to?

### CODE REVIEW

**Comment by bumi** [comment]
line 98 should also be changed, shouldn't it? 

``` python
if request.args.get('timestamp', None):
         data['timestamp'] = request.args.get('time')
```

**Comment by jlark** [comment]
Correct.

Changing.

**Comment by bumi** [comment]
re CI: I am running a influx instance on travis: 
https://github.com/GreatLakesEnergy/sesh-api-helper/blob/master/.travis.yml#L6-L9

ahh true, the defaults changed, so we should set the host to localhost and no user and passwd in the test_api.py

**Comment by jlark** [comment]
How do you run an influx on travis??
Can you send that to me in an email?

Mobile typing

On Mon, Feb 29, 2016 at 7:47 AM -0800, "Michael Bumann" notifications@github.com wrote:

re CI: I am running a influx instance on travis: 

https://github.com/GreatLakesEnergy/sesh-api-helper/blob/master/.travis.yml#L6-L9

ahh true, the defaults changed, so we should set the host to localhost and no user and passwd in the test_api.py

**Pull request merged**
